/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "home": [],
    "login": [],
    "registro.form": [],
    "registro.admin": [],
    "registro.admin.store": [],
    "registro-empresa.form": [],
    "registro-empresa.store": [],
    "usuarios.index": [],
    "usuarios.create": [],
    "usuarios.store": [],
    "dashboard": [],
    "logout": [],
    "roles.index": [],
    "roles.create": [],
    "roles.store": [],
    "roles.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "roles.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "roles.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "roles.asignar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permisos.index": [],
    "permisos.create": [],
    "permisos.store": [],
    "permisos.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permisos.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "permisos.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "roles_permisos.index": [],
    "admin.actualizar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.editar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance.edit": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
